# Configuration for GitHub repository

# Repository topics
topics:
  - ecommerce
  - online-store
  - fashion-website
  - tailwindcss
  - nodejs
  - express
  - mongodb
  - responsive-design
  - shopping-cart
  - dark-mode
  - web-development
  - javascript

# Labels for issues and pull requests
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
